apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-HPA.yaml
  - frontend-HPA.yaml
  - pdb-backend.yaml
  - pdb-frontend.yaml
  - pdb-redis.yaml 
  - pdb-database.yaml
