apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: bookstore
  labels:
    app: mysql
    tier: database
type: Opaque
data:
  MYSQL_USER: Ym9va3N0b3Jl
  MYSQL_PASSWORD: Ym9va3N0b3JlMTIz
  MYSQL_ROOT_PASSWORD: c3Ryb25nLXJvb3QtcGFzc3dvcmQ=
