apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - database.yaml
  - database-service.yaml
  - redis.yaml
  - redis-service.yaml
  - backend.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress-frontend.yaml
  - bookstore-tls.yaml
  

configMapGenerator:
  - name: mysql-init-script
    files:
      - init.sql=./init.sql  # loads k8s/base/init.sql
